# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Build executable
      run: |
        poetry run pyinstaller --name key_presser_app --onefile main.py
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: key_presser_app
        path: dist/key_presser_app
        if-no-files-found: error
