name: Build and Attach to Release

on:
  release:
    types: [created]


jobs:
  build_and_publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Build executable
        run: |
          poetry run pyinstaller --name key_presser_app --onefile src/main.py
      - name: Release asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/key_presser_app --clobber